Lobbies
directivegames/DriftUE4Base pull request #14
Opened 2021-10-07 14:41 UTC by Indexu

2021-10-07 14:58 UTC, Indexu commented
@judgeaxl You can merge this if you don't find anything odd about it.

2021-10-11 04:20 UTC, judgeaxl requested changes

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	RequestManager = RootRequestManager;
Could use MoveTemp here to avoid a copy

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	CurrentLobbyURL = DriftEndpoints.my_lobby;
The CurrentLobby URLs were supposed to be removed, since they require potentially costly lookup on the root resource, which is supposed to be info only. They'll need to be filled in after an initial query, if the game needs it.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +			UE_LOG(LogDriftLobby, Warning, TEXT("No lobby found when querying for initial state. Weird."));
I suggest replacing "weird" here with a description of the action that will be taken, i.e. resetting the lobby (session) or something like that.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyDeletedDelegate.Broadcast(OldLobbyId);
If this is the first thing that happens, will anyone know about this lobby and care about this notification? Might just be confusing if I start up a new game and get told my lobby is missing. Depends on who listens to this and what they do with it of course.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +void FDriftLobbyManager::ExtractLobby(const FDriftLobbyResponse& LobbyResponse, bool bUpdateURLs)
I can't help but feeling that the name `ExtractLobby` suggests it would return the lobby information, not set it internally. `SetLobbyDataFromResponse` perhaps?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +			UE_LOG(LogDriftLobby, Error, TEXT("Found existing lobby but player is not a member"));
Should the CurrentLobbyURL members not be reset here?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +#if UE_BUILD_DEBUG || UE_BUILD_DEVELOPMENT
There's another configuration mode called "test" which is an optimized build with development features, and which also supports the console, so you might want to change the expression to not shipping. Not required, just a FYI

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +		(void)Delegate.ExecuteIfBound(false, "", "No backend connection");
There's been a debate regarding if it makes sense to fire this delegate or not, when the task never gets started, as you have to deal with a different ordering as a caller. The delegate will normally fire success or failure after the initial call has returned, meaning the caller has been able to store state, configure handlers, and what else. When preconditions fail, the callback happens before the initial call has returned, so the handler needs to be careful in what context it processes the result.

In new code I suggest we rely on the bool return to indicate "failed to initiate the request", and the delegate only to be used to signal the result of the request if it actually got started.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +			(void)Delegate.ExecuteIfBound(false, "", "Lobby found, but you're not registered as a member of the lobby");
Should the lobby state be reset here?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	const FString URL = FString::Printf(TEXT("%s%s/members"), *LobbiesURL, *LobbyId); // Manual URL constructing. Maybe figure out a better way to get the members resource of the lobby
The pattern to use, if we have to manually construct URLs, and we should still avoid that as much as possible, is to expose a template URL in the root resource, like `lobby_members_template = https://foo.fg-api.com/drift/lobbies/{lobby_id}/members` and use replace on the URL before using it, and example can be found in `FDriftBase::SavePlayerGameStateImpl`.

In this particular case, where do we get the Lobby ID from? Can't it return the relevant URL too?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	UE_LOG(LogDriftLobby, Log, TEXT("Leaving current lobby. Locally cached lobby: '%s'"), *CurrentLobbyId);
If CurrentLobbyId is empty here, but CurrentLobbyMemberURL is not, what's the state? CurrentLobbyId is used here and below even if it's determined to be empty.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	ApplyCurrentPlayerProperties();
If the request later fails below, won't this be out of sync?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +			UE_LOG(LogDriftLobby, Warning, TEXT("Player '%d' invalid in locally cached lobby. Maybe out of sync with server"));
Missing a return/fail here?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +		URL = FString::Printf(TEXT("%s%s/members/%d"), *LobbiesURL, *CurrentLobbyId, MemberPlayerId); // Manual URL constructing as a last resort
Until replaced with a template, per the above use case, this should be separated out to a method to avoid duplication

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +		return true;
The delegate should be fired here too for consistency with the failure cases, but on the other hand, as per not at the top of the file, perhaps the delegates should not fire at all if the request never fires.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	    CurrentLobby->LobbyStatus = EDriftLobbyStatus::Failed;
Is it possible to recover from this error or is the lobby now failed forever?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +		UE_LOG(LogDriftLobby, Error, TEXT("FDriftLobbyManager::HandleLobbyEvent - Event data doesn't contain 'lobby_id'. Discarding the event. Current cached lobby id: '%s'. Querying for the current lobby
Are all lobby events supposed to contain a lobby_id? If so, I don't think this should query the lobby.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	if (LobbyId != CurrentLobbyId)
I'm not entirely happy with all the QueryLobby calls when the data is not matching expectations. Is there a reason why these events would contain the wrong data?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberJoinedDelegate.Broadcast(CurrentLobbyId);
Would it not make sense to pass along some information about the player that joined?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberUpdatedDelegate.Broadcast(CurrentLobbyId);
Would it not make sense to pass along some information about the player that got updated?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberLeftDelegate.Broadcast(CurrentLobbyId);
Would it not make sense to pass along some information about the player that got deleted?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberKickedDelegate.Broadcast(CurrentLobbyId);
Would it not make sense to pass along some information about the player that got kicked?

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +	if (EventName == TEXT("LobbyUpdated"))
When using non-braced single line ifs like this, I suggest instead writing:

`if (condition) { return result; }`

as that is resistant to future refactorings which might introduce additional lines, plus it's even more compact.

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftLobbyManager.cpp
> +bool FDriftLobbyManager::ExtractMembers(const JsonValue& EventData)
Same problem as ExtractLobby, the name suggests that it would return the members, not magically set them internally

2021-10-11 04:20 UTC, judgeaxl commented on Drift/Private/DriftSchemas.cpp
> +		&& SERIALIZE_PROPERTY(context, my_lobby)
As per separate discussion, these are problematic

2021-10-11 13:58 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +			(void)Delegate.ExecuteIfBound(false, "", "Lobby found, but you're not registered as a member of the lobby");
Probably

2021-10-11 14:00 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	const FString URL = FString::Printf(TEXT("%s%s/members"), *LobbiesURL, *LobbyId); // Manual URL constructing. Maybe figure out a better way to get the members resource of the lobby
We get the ID from user input, so impossible to get the URL beforehand via some drift-base response.

Will take a look at the SavePlayerGameStateImpl

2021-10-11 14:05 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	UE_LOG(LogDriftLobby, Log, TEXT("Leaving current lobby. Locally cached lobby: '%s'"), *CurrentLobbyId);
With the removal of my_xyz URLs, the state is consistent and I don't think it's possible to get in such a state.

2021-10-11 14:16 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	ApplyCurrentPlayerProperties();
Will rework this.
Same with update lobby.

2021-10-11 14:20 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +			UE_LOG(LogDriftLobby, Warning, TEXT("Player '%d' invalid in locally cached lobby. Maybe out of sync with server"));
Perhaps.
This kick code has never been run before since I didn't have time to add it to the UI and properly test it prior to the tournament.

2021-10-11 14:21 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +		return true;
Then should the return value be false? Since the request never fires.

2021-10-11 14:22 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	    CurrentLobby->LobbyStatus = EDriftLobbyStatus::Failed;
You can recover from this, yes.
It might not be clear, but this happens when the start match failed. You can retry starting the match.

2021-10-11 14:25 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +		UE_LOG(LogDriftLobby, Error, TEXT("FDriftLobbyManager::HandleLobbyEvent - Event data doesn't contain 'lobby_id'. Discarding the event. Current cached lobby id: '%s'. Querying for the current lobby
They are all supposed to, yes.
In the case that for some mystical reason, drift-base doesn't provide a message in the lobby message queue with a lobby id, then the message is borked, this logs out and syncs with the server the current lobby state via QueryLobby.

Then we get notified of this via Sentry and should take a look at what happened.
Ideally, this should never be run.

2021-10-11 14:26 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	if (LobbyId != CurrentLobbyId)
Paranoia.

Also, if someone in the future makes changes to the backend and doesn't update the C++ to follow along, we get a bunch of logs saying stuff is borked.

2021-10-11 14:26 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberJoinedDelegate.Broadcast(CurrentLobbyId);
It would, yes.
We can add that in the future if we need it.

2021-10-11 14:27 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberUpdatedDelegate.Broadcast(CurrentLobbyId);
It would, yes.
We can add that in the future if we need it.

2021-10-11 14:27 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberLeftDelegate.Broadcast(CurrentLobbyId);
It would, yes.
We can add that in the future if we need it.

2021-10-11 14:27 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyMemberKickedDelegate.Broadcast(CurrentLobbyId);
It would, yes.
We can add that in the future if we need it.

2021-10-11 14:28 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	if (EventName == TEXT("LobbyUpdated"))
It was a copy pasta job from somewhere else in Drift.

I can add the braces if you want.

2021-10-11 14:28 UTC, Indexu commented on Drift/Private/DriftSchemas.cpp
> +		&& SERIALIZE_PROPERTY(context, my_lobby)
Removed

2021-10-11 14:28 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	CurrentLobbyURL = DriftEndpoints.my_lobby;
Removed

2021-10-11 14:29 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +				OnLobbyDeletedDelegate.Broadcast(OldLobbyId);
Remnant from copy pasting the query lobby code.
Removed.

2021-10-11 14:31 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +void FDriftLobbyManager::ExtractLobby(const FDriftLobbyResponse& LobbyResponse, bool bUpdateURLs)
I don't know where I got that habit, but for some reason I always name functions that parse and set member variables from some response/arg/input/output `ExtractXYZ`.

2021-10-11 14:31 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +			UE_LOG(LogDriftLobby, Error, TEXT("Found existing lobby but player is not a member"));
After removing the my urls, this is no longer an issue.

2021-10-11 14:33 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +		(void)Delegate.ExecuteIfBound(false, "", "No backend connection");
hmm...
I'm using the third param in the delegate as the error string which is then used in UI to notify the user what went wrong. Could also be a status code and looked up in some localization file, but same issue.
Hard to know what goes wrong just from 'false'.

Ideas?

2021-10-11 15:30 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	const FString URL = FString::Printf(TEXT("%s%s/members"), *LobbiesURL, *LobbyId); // Manual URL constructing. Maybe figure out a better way to get the members resource of the lobby
Added template urls to drift-base and string replace to construct the URLs.

2021-10-12 14:50 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +bool FDriftLobbyManager::ExtractMembers(const JsonValue& EventData)
Renamed to CacheLobby and CacheMembers.

Saw that terminology was used elsewhere in Drift.

2021-10-12 14:50 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +void FDriftLobbyManager::ExtractLobby(const FDriftLobbyResponse& LobbyResponse, bool bUpdateURLs)
Renamed to CacheLobby and CacheMembers.

Saw that terminology was used elsewhere in Drift.

2021-10-12 14:54 UTC, Indexu commented on Drift/Private/DriftLobbyManager.cpp
> +	if (EventName == TEXT("LobbyUpdated"))
Added the braces. Looks nifty.

2021-10-13 13:13 UTC, judgeaxl approved these changes

2021-10-13 13:28 UTC, merged